version: '3'

dotenv:
  - .env

vars:
  REGISTRY: localhost:5001
  REPOSITORY: playstack

tasks:
  default:
    aliases: [list]
    silent: true
    desc: "List all available tasks"
    cmds:
      - task --list-all
        
  encrypt:
    silent: true
    desc: "Encrypt .env and terraform.tfvars files"
    cmds:
      - sops -e -i .env
      - sops -e -i terraform/environments/terraform.tfvars
      - sops -e -i k8s/helm/values.secret.yaml
      - sops -e -i example.env

  decrypt:
    silent: true
    desc: "Decrypt .env and terraform.tfvars files"
    cmds:
      - sops -d -i .env
      - sops -d -i terraform/environments/terraform.tfvars
      - sops -d -i k8s/helm/values.secret.yaml
      - sops -d -i example.env

  tf:plan:
    silent: true
    desc: "Generate Terraform/OpenTofu plan for the environment"
    dir: terraform/environments
    cmds: [tofu plan]

  tf:apply:
    silent: true
    var:
      approve: false
    dir: terraform/environments
    desc: "Apply Terraform/OpenTofu plan to the environment"
    cmds: 
      - tofu apply
  
  tf:apply:auto:
    silent: true
    dir: terraform/environments
    desc: "Apply Terraform/OpenTofu plan (auto approve)"
    cmds:
      - tofu apply --auto-approve
  
  tf:unlock:
    silent: true
    dir: terraform/environments
    var:
      ID: 
    desc: "Apply Terraform/OpenTofu plan (auto approve)"
    cmds:
      - tofu force-unlock {{.ID}}

  tf:destroy:
    silent: true
    dir: terraform/environments
    desc: "Destroy Terraform/OpenTofu managed infrastructure"
    cmds: [tofu destroy]

  tf:validate:
    silent: true
    dir: terraform/environments
    desc: "Validate Terraform/OpenTofu configuration"
    cmds: [tofu validate]

  tf:output:
    silent: true
    dir: terraform/environments
    desc: "Initialize Terraform/OpenTofu with remote backend"
    cmds: [tofu output]
  
  tf:init:
    silent: true
    dir: terraform/environments
    desc: "Initialize Terraform/OpenTofu with remote backend"
    cmds: 
    - |
      tofu init \
      -backend-config="address=https://gitlab.com/api/v4/projects/$GITLAB_PROJECT_ID/terraform/state/$TF_STATE_NAME" \
      -backend-config="lock_address=https://gitlab.com/api/v4/projects/$GITLAB_PROJECT_ID/terraform/state/$TF_STATE_NAME/lock" \
      -backend-config="unlock_address=https://gitlab.com/api/v4/projects/$GITLAB_PROJECT_ID/terraform/state/$TF_STATE_NAME/lock" \
      -backend-config="username=$GITLAB_USERNAME" \
      -backend-config="password=$GITLAB_ACCESS_TOKEN" \
      -backend-config="lock_method=POST" \
      -backend-config="unlock_method=DELETE" \
      -backend-config="retry_wait_min=5"
        
  swagger:init:
    desc: Generate Swagger documation of Gen Service
    cmds:
      - |
        swag init --parseDependency \
        --parseInternal \
        --packageName swagger \
        --dir ./backend/server \
        -g ../main.go \
        -o ./backend/swagger

  work:sync:
    cmds: 
      - cd libs/core && go mod tidy
      - cd libs/idp && go mod tidy
      - cd libs/queue && go mod tidy
      - cd libs/storage && go mod tidy
      - cd backend && go mod tidy
      - cd consumer && go mod tidy

  sonar:
    var:
      SONAR_ORG: ${SONAR_ORG}
      SONAR_PROJECT_KEY: ${SONAR_PROJECT_KEY}
    cmds: 
      - |
        sonar-scanner \
        -Dsonar.organization={{.SONAR_ORG}} \
        -Dsonar.projectKey={{.SONAR_PROJECT_KEY}} \
        -Dsonar.projectVersion=0.1.0 \
        -Dsonar.sources=. \
        -Dsonar.exclusions="**/*_test.go,**/vendor/**,**/testdata/**,**/tmp/**,**/docs/**,**/swagger/**,**/migration/**" \
        -Dsonar.tests=. \
        -Dsonar.test.inclusions="**/*_test.go" \
        -Dsonar.go.coverage.reportPaths=coverage.out \
        -Dsonar.go.tests.reportPaths=test-report.json \
        -Dsonar.sourceEncoding=UTF-8 \
        -Dsonar.scm.provider=git \
        -Dsonar.scm.revision=${CI_COMMIT_SHA} \
        -Dsonar.links.homepage=${CI_PROJECT_URL} \
        -Dsonar.links.ci=${CI_PIPELINE_URL} \
        -Dsonar.links.scm=${CI_REPOSITORY_URL} \
        -Dsonar.branch.name=${CI_COMMIT_REF_NAME}
  
  helm:template:
    silent: true
    dir: k8s
    cmds: [helm template playstack ./helm] 