{{- if .Values.transcoder.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.transcoder.name }}"
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Values.appVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/environment: {{ .Values.environment }}
spec:
  maxReplicaCount: {{ .Values.transcoder.maxReplicaCount }}
  pollingInterval: {{ .Values.transcoder.pollingInterval }}
  successfulJobsHistoryLimit: {{ .Values.transcoder.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.transcoder.failedJobsHistoryLimit }}
  jobTargetRef:
    template:
      spec:
        restartPolicy: Never
        imagePullSecrets:
          - name: playstack-image-registry-sk
        containers:
          - name: {{ .Chart.Name }}-{{ .Values.transcoder.name }}
            image: {{ .Values.registry }}/{{ .Chart.Name }}/{{ .Values.transcoder.name }}:{{ .Values.appVersion }}
            envFrom:
              - configMapRef:
                  name: "{{ .Chart.Name }}-{{ .Values.transcoder.name }}-cm"
              {{- range .Values.transcoder.configMapRef }}
              - configMapRef:
                  name: {{ $.Chart.Name }}-{{ . }}-cm
              {{- end }}
              {{- range .Values.transcoder.secretRef }}
              - secretRef:
                  name: {{ $.Chart.Name }}-{{ . }}-sk
              {{- end }}
            resources:
              requests:
                cpu: {{ .Values.transcoder.requests.cpu }}
                memory: {{ .Values.transcoder.requests.memory }}
              limits:
                cpu: {{ .Values.transcoder.limits.cpu }}
                memory: {{ .Values.transcoder.limits.memory }}
  triggers:
    - type: {{ .Values.transcoder.trigger.type }}
      authenticationRef:
        name: {{ .Chart.Name }}-{{ .Values.transcoder.triggerAuthorization.name }}-ta
      metadata:
        queueURL: "{{ .Values.transcoder.trigger.queueURL }}"
        queueLength: {{ .Values.transcoder.trigger.queueLength | int }}
        awsRegion: {{ .Values.transcoder.trigger.awsRegion }}
{{- end }}