{{ if .Values.transcoder.enabled }}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ .Chart.Name }}-{{ .Values.transcoder.triggerAuthorization.name }}-ta
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Values.appVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/environment: {{ .Values.environment }}
spec:
  secretTargetRef:
    - parameter: awsAccessKeyID
      name: {{ .Chart.Name }}-{{ .Values.transcoder.triggerAuthorization.secretTarget }}-sk
      key: AWS_ACCESS_KEY_ID
    - parameter: awsSecretAccessKey
      name: {{ .Chart.Name }}-{{ .Values.transcoder.triggerAuthorization.secretTarget }}-sk
      key: AWS_SECRET_ACCESS_KEY
{{ end }}