{{- if $.Values.secret }}
{{- range $secretName, $secretData := $.Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Chart.Name }}-{{ $secretName }}-sk
  namespace: {{ default $.Release.Namespace (default $.Values.namespace $secretData.namespace) | quote }}
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/version: {{ $.Values.appVersion }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/environment: {{ $.Values.environment }}
    sealedsecrets.bitnami.com/managed: true
    {{- if $secretData.labels }}
    {{- range $key, $value := $secretData.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
type: Opaque
data:
{{- range $key, $value := $secretData.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
---
{{- end }}
{{- end }}
