{{ if .Values.backend.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.backend.name }}-cm"
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Values.appVersion }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/environment: {{ .Values.environment }}
data:
  SERVICE_ENV: {{ .Values.environment }}
{{ end }}