apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playstack-argoproj
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/subrotokumar/playstack-ops.git
    targetRevision: HEAD
    path: helm
    helm:
      valueFiles:
        - helm/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: playstack