secret:
    basicauth:
        data:
            BASIC_AUTH_USERNAME: XXXX
            BASIC_AUTH_PASSWORD: XXXX
    database:
        data:
            DB_USERNAME: XXXX
            DB_PASSWORD: XXXX
            DB_HOST: XXXX
            DB_PORT: "XXXX"
            DB_NAME: XXXX
            DB_SSL_MODE: XXXX
    aws:
        data:
            AWS_REGION: XXXX
            AWS_ACCESS_KEY_ID: XXXX
            AWS_SECRET_ACCESS_KEY: XXXX
    cognito:
        data:
            COGNITO_CLIENT_ID: XXXX
            COGNITO_CLIENT_SECRET: XXXX
            COGNITO_USER_POOL_ID: XXXX
    s3:
        data:
            RAW_MEDIA_BUCKET: XXXX
            MEDIA_BUCKET: XXXX
    repo-creds:
        namespace: argocd
        labels:
            argocd.argoproj.io/secret-type: repo-creds
        data:
            type: git
            url: https://gitlab.com/XXXX/YYYY.git
            password: XXXX
            username: XXXX